project_id = "mykcfrlcrluvwnonbjzu"

[functions.scrape-italo]
verify_jwt = false

[functions.scrape-marcon]
verify_jwt = false

[functions.scrape-alfa]
verify_jwt = false

[functions.compare-products-gtin]
verify_jwt = false

[functions.compare-products-advanced]
verify_jwt = false
